version: '3.9'
services:
  nginx:
    image: sparkpos/docker-nginx-php:8.1-alpine
    container_name: drupal9
    hostname: drupal9.docker
    environment:
      - VIRTUAL_HOST=drupal9.docker
      - DRUPAL_WEB_ROOT=web
      - PHP_MEM_LIMIT=2048M
    volumes:
      - /Users/zhouitpro/www/drupal9:/var/www/html
    restart: always
networks:
  default:
    name: proxy
    external: true
