version: '3.9'
services:
  nginx:
    image: sparkpos/docker-nginx-php:8.2-alpine
    container_name: farmos
    hostname: farmos.docker
    environment:
      - VIRTUAL_HOST=farmos.docker
      - DRUPAL_WEB_ROOT=web
    volumes:
      - /Users/zhouitpro/www/farmos:/var/www/html
    restart: always
networks:
  default:
    name: proxy
    external: true
